### ISSUE TITLE
Unable to download pre-trained model

### ISSUE THREAD

**Issue by deep0learning** [aws-samples/d-SNE#1]
Hi,
Thank you for your nice work. 
I was trying to run your code on my machine and run this script `sh scripts/download_pretrained_models.sh`

showing error.

sh scripts/download_pretrained_models.sh
--2019-08-15 14:59:41--  https://s3-us-west-2.amazonaws.com/domain-adaptation-exps/models/pretrained/vgg16.params
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.216.216
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.216.216|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-08-15 14:59:41 ERROR 403: Forbidden.

--2019-08-15 14:59:41--  https://s3-us-west-2.amazonaws.com/domain-adaptation-exps/models/pretrained/resnet101_v2.params
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.216.216
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.216.216|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-08-15 14:59:42 ERROR 403: Forbidden.

--2019-08-15 14:59:42--  https://s3-us-west-2.amazonaws.com/domain-adaptation-exps/models/pretrained/resnet152_v2.params
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.216.216
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.216.216|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-08-15 14:59:43 ERROR 403: Forbidden.

--2019-08-15 14:59:43--  https://s3-us-west-2.amazonaws.com/domain-adaptation-exps/models/pretrained/densenet169.params
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.216.216
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.216.216|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-08-15 14:59:43 ERROR 403: Forbidden.

--2019-08-15 14:59:43--  https://s3-us-west-2.amazonaws.com/domain-adaptation-exps/models/pretrained/densenet201.params
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.216.216
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.216.216|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-08-15 14:59:44 ERROR 403: Forbidden.

**Comment by xzhou33** [comment]
Sorry for the inconvenience. The download link has been fixed in the linked request. You should be able to downloand the pretrained models now.
