### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by deep0learning** [aws-samples/d-SNE#2]
I run the code and got the following error. Can you please help to sort out this problem?
`python main_sda.py --method v0 --cfg cfg/offices.json --src A --tgt D --nc 31 --train-src --log-itv 0 --flip --random-color --random-crop --model-path pretrained/vgg16.params --fn --hybridize
`

 from train_val.custom_layers import AngularLinear, L2Normalization
ImportError: cannot import name 'AngularLinear'

**Comment by xzhou33** [comment]
Sorry for the inconvenience. The download link has been fixed in the linked request. You should be able to downloand the pretrained models now.

**Comment by xzhou33** [comment]
Thanks for trying out the algorithm. The import issue has been fixed in the linked request.
