### ISSUE TITLE
Unable to download datasets

### ISSUE THREAD

**Issue by halbielee** [aws-samples/d-SNE#5]
Hello,
Thank you for sharing you wonderful work!

I tried to run your code and I got error when running ```sh scripts/download_digits_datasets.sh```

Messages are here.
--2019-09-15 17:17:14--  https://s3-us-west-2.amazonaws.com/domain-adaptation-exps/datasets/MNIST/mnist.pkl             Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 54.231.168.212                                     Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|54.231.168.212|:443... connected.                 HTTP request sent, awaiting response... 403 Forbidden                                                                   2019-09-15 17:17:14 ERROR 403: Forbidden.                                                                                                                                                                                                       --2019-09-15 17:17:14--  https://s3-us-west-2.amazonaws.com/domain-adaptation-exps/datasets/MNIST-M/mnist_m.pkl         Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 54.231.168.212                                     Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|54.231.168.212|:443... connected.                 HTTP request sent, awaiting response... 403 Forbidden                                                                   2019-09-15 17:17:15 ERROR 403: Forbidden.                                                                                                                                                                                                       --2019-09-15 17:17:15--  https://s3-us-west-2.amazonaws.com/domain-adaptation-exps/datasets/SVHN/svhn.pkl               Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 54.231.168.212                                     Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|54.231.168.212|:443... connected.                 HTTP request sent, awaiting response... 403 Forbidden                                                                   2019-09-15 17:17:15 ERROR 403: Forbidden.                                                                                                                                                                                                       --2019-09-15 17:17:15--  https://s3-us-west-2.amazonaws.com/domain-adaptation-exps/datasets/USPS/usps.pkl               Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 54.231.168.212                                     Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|54.231.168.212|:443... connected.                 HTTP request sent, awaiting response... 403 Forbidden                                                                   2019-09-15 17:17:16 ERROR 403: Forbidden. 

Can you provide a vaild link for dataset?

Thank you!

**Comment by ShownX** [comment]
Hi, it seems that the S3 bucket permission is limited. Will take a look with my colleague ang get back to you soon.

**Comment by orchidmajumder** [comment]
We have added a script to create the datasets in the required format after you download it from the public source. Please take a look. The example only does for MNIST, for other dataset, please modify the script to point to relevant dataset files.
